### ISSUE TITLE
Add API call to get proxy IP address

### ISSUE THREAD

**Issue by vhryhorchuk-amplify** [amplify-education/amplium#11]
Hi!
Is it possible to add API calls available in standard Grid?
For example, I miss the `GET [address]/grid/api/testsession?session={sessionId}` which gives information about proxy IP running webdriver.
Thanks.

**Comment by jconstance-amplify** [comment]
Hey @vhryhorchuk-amplify, would you be interested in sending a PR to support this?

**Comment by vhryhorchuk-amplify** [comment]
Should be implemented after https://github.com/amplify-education/amplium/pull/13 merge
